package main

import (
	"os"
	"fmt"
	"io/ioutil"
)

const TEMPLATE = `//generated by github.com/bsick7/go-versioner
package main

const VERSION = "%s"
`

func main() {
	if v, err := ioutil.ReadFile("VERSION"); err != nil {
		fmt.Fprintf(os.Stderr, "could not load VERSION file: %s", err)
		os.Exit(1)
	} else {
		data := fmt.Sprintf(TEMPLATE, v)
		if err := ioutil.WriteFile("version.go", []byte(data), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "could not write version.go file: %s", err)
			os.Exit(1)
		}
	}
}
